### ISSUE TITLE
experiencing RequestedMethod could not be found errors

### ISSUE THREAD

**Issue by lteffertiller** [SeydX/homebridge-bravia-tvos#112]
I'm getting these errors in my logs every 10 seconds, and I'm not sure what is being called or referenced. 

`[11/30/2020, 10:00:27 AM] [BraviaTVOS] Error: Requested method (%s) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:138:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:194:10)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:115:46)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:177:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

I looked for the file path `/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx` but it's not there... would there be any reason why? 

This is on a clean install of Rasp Pi and brand new install of Homebridge and homebridge-bravia-tvos.

Here is the config file presently:

```
            "platform": "BraviaOSPlatform",
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Living Room TV",
                    "ip": "<ip>",
                    "mac": "<mac>",
                    "port": 80,
                    "timeout": 30,
                    "psk": "<psk>",
                    "model": "X750H",
                    "apps": [
                        "YouTube",
                        "Disney+"
                    ],
                    "commands": [
                        "VolumeUp",
                        "VolumeDown"
                    ],
                    "speaker": {
                        "output": "headphone",
                        "increaseBy": 1,
                        "reduceBy": 1
                    },
                    "remote": [
                        {
                            "command": "Up",
                            "target": "ARROW_UP"
                        },
                        {
                            "command": "Down",
                            "target": "ARROW_DOWN"
                        },
                        {
                            "command": "Left",
                            "target": "ARROW_LEFT"
                        },
                        {
                            "command": "Right",
                            "target": "ARROW_RIGHT"
                        },
                        {
                            "command": "Confirm",
                            "target": "SELECT"
                        },
                        {
                            "command": "VolumeUp",
                            "target": "VOLUME_UP"
                        },
                        {
                            "command": "VolumeDown",
                            "target": "VOLUME_DOWN"
                        },
                        {
                            "command": "Return",
                            "target": "BACK"
                        }
                    ]
```

**Comment by SeydX** [comment]
hey @lteffertiller 

can u try v4.1.6 pls - this should give more infore about the requested method.

And also enable ``debug`` in config pls

**Comment by lteffertiller** [comment]
Just updated and enabled debug- now getting this:
`[12/1/2020, 10:35:53 AM] [BraviaTVOS] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:138:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:194:10)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:115:46)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:177:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by SeydX** [comment]
@lteffertiller 

Could you successfully run the TV with another plugin before?

**Comment by lteffertiller** [comment]
this is the first time i've tried- i haven't used it on another plugin before

**Comment by lteffertiller** [comment]
if it helps, when i make remote control presses, it logs 404 errors. not sure if they're correlated.

**Comment by SeydX** [comment]
@lteffertiller 

Is anything else working? It seems that your tv doesn’t support the Sony API. Which model?

**Comment by lteffertiller** [comment]
it's the Sony X750H. power and input controls work fine, it's just remote controls and the random logs for some reason. the TV is completely up to date as well.

**Comment by SeydX** [comment]
@lteffertiller 

Hmm, strange.. is it always the same error?

``Error: Requested method (getPlayingContentInfo) could not be found! ``

One another thing that would be very helpful is to enable homebridge debug and put ``bravia:*`` as below:

![C46B97A9-B47E-4B95-94C1-D73F206C624D](https://user-images.githubusercontent.com/34152761/100797434-669c8c00-3422-11eb-9f5f-4e8a231bf8b3.gif)

**Comment by lteffertiller** [comment]
it's the exact same error, yes. i just enabled the debug flag- i'll come back with logs in a few!

**Comment by SeydX** [comment]
@lteffertiller 

Allright. Please post the whole log here from restart. Not only the line with the error

**Comment by lteffertiller** [comment]
here you go- this is all of it up until it starts repeating logs again:

`[12/1/2020, 4:15:31 PM] [HB Supervisor] OS: Linux 5.4.72+ arm
[12/1/2020, 4:15:31 PM] [HB Supervisor] Node.js v14.15.0 /usr/local/bin/node
[12/1/2020, 4:15:31 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[12/1/2020, 4:15:31 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/1/2020, 4:15:31 PM] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[12/1/2020, 4:16:00 PM] [Homebridge UI] Homebridge Config UI X v4.34.0 is listening on :: port 8581
[12/1/2020, 4:16:06 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[12/1/2020, 4:16:06 PM] [HB Supervisor] Starting Homebridge with custom env: {"DEBUG":"bravia:*"}
[12/1/2020, 4:16:07 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 14562
[12/1/2020, 4:16:19 PM] Loaded config.json with 1 accessories and 3 platforms.
[12/1/2020, 4:16:20 PM] ---
[12/1/2020, 4:16:25 PM] Loaded plugin: homebridge-bravia-tvos@4.1.6
[12/1/2020, 4:16:28 PM] Registering platform 'homebridge-bravia-tvos.BraviaOSPlatform'
[12/1/2020, 4:16:28 PM] ---
[12/1/2020, 4:16:28 PM] Loaded plugin: homebridge-config-ui-x@4.34.0
[12/1/2020, 4:16:28 PM] Registering platform 'homebridge-config-ui-x.config'
[12/1/2020, 4:16:28 PM] ---
[12/1/2020, 4:16:29 PM] Loaded plugin: homebridge-nest@4.5.1
[12/1/2020, 4:16:29 PM] Registering platform 'homebridge-nest.Nest'
[12/1/2020, 4:16:29 PM] ---
[12/1/2020, 4:16:34 PM] Loaded plugin: homebridge-roomba@1.0.1
[12/1/2020, 4:16:34 PM] Registering accessory 'homebridge-roomba.Roomba'
[12/1/2020, 4:16:34 PM] ---
[12/1/2020, 4:16:34 PM] Loading 3 platforms...
[12/1/2020, 4:16:34 PM] [Config] Initializing config platform...
[12/1/2020, 4:16:34 PM] [Config] Running in Service Mode
[12/1/2020, 4:16:34 PM] [Nest] Initializing Nest platform...
[12/1/2020, 4:16:34 PM] [BraviaTVOS] Initializing BraviaOSPlatform platform...
[12/1/2020, 4:16:34 PM] Loading 1 accessories...
[12/1/2020, 4:16:34 PM] [Roomba] Initializing Roomba accessory...
[12/1/2020, 4:16:34 PM] [BraviaTVOS] Living Room TV Speaker: Configuring accessory...
[12/1/2020, 4:16:34 PM] [Nest] Fetching Nest devices.
[12/1/2020, 4:16:34 PM] [Nest] Authenticating via Google.
[12/1/2020, 4:16:34 PM] [BraviaTVOS] Living Room TV: Configuring accessory...
Setup Payload:
X-HM://00251NT8MOL67
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 952-83-398 │     
    └────────────┘     
                       
[12/1/2020, 4:16:35 PM] Homebridge is running on port 51317.
2020-12-01T21:16:36.178Z bravia:service:avContent Method types not initialized yet. Initializing available method types before continue
2020-12-01T21:16:36.187Z bravia:service:avContent Executing action getVersions (1.0)
2020-12-01T21:16:36.196Z bravia:request Initializing request for http://192.168.4.46:80/sony/avContent
2020-12-01T21:16:36.250Z bravia:request Request data { id: 3, method: 'getVersions', version: '1.0', params: [] }
2020-12-01T21:16:36.254Z bravia:request Request options {
  'Content-Type': 'text/xml; charset=UTF-8',
  SOAPACTION: '"urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"',
  'X-Auth-PSK': 'bv2121'
}
[12/1/2020, 4:16:36 PM] [BraviaTVOS] Living Room TV: Configured!
[12/1/2020, 4:16:36 PM] Living Room TV is running on port 38275.
[12/1/2020, 4:16:36 PM] Please add [Living Room TV] manually in Home app. Setup Code: 952-83-398
2020-12-01T21:16:37.052Z bravia:service:avContent Executing action getMethodTypes (1.0)
2020-12-01T21:16:37.086Z bravia:request Initializing request for http://192.168.4.46:80/sony/avContent
2020-12-01T21:16:37.096Z bravia:request Request data { id: 3, method: 'getMethodTypes', version: '1.0', params: [ '1.0' ] }
2020-12-01T21:16:37.121Z bravia:request Request options {
  'Content-Type': 'text/xml; charset=UTF-8',
  SOAPACTION: '"urn:schemas-sony-com:service:IRCC:1#X_SendIRCC"',
  'X-Auth-PSK': 'bv2121'
}
2020-12-01T21:16:38.764Z bravia:service:avContent Registering method getContentCount (1.0) for avContent
2020-12-01T21:16:38.770Z bravia:service:avContent Registering parameter "source" for getContentCount (1.0)
2020-12-01T21:16:38.773Z bravia:service:avContent Registering parameter "type" for getContentCount (1.0)
2020-12-01T21:16:38.779Z bravia:service:avContent Registering method getContentList (1.0) for avContent
2020-12-01T21:16:38.783Z bravia:service:avContent Registering parameter "source" for getContentList (1.0)
2020-12-01T21:16:38.786Z bravia:service:avContent Registering parameter "stIdx" for getContentList (1.0)
2020-12-01T21:16:38.789Z bravia:service:avContent Registering parameter "cnt" for getContentList (1.0)
2020-12-01T21:16:38.792Z bravia:service:avContent Registering parameter "type" for getContentList (1.0)
2020-12-01T21:16:38.796Z bravia:service:avContent Registering method getCurrentExternalInputsStatus (1.0) for avContent
2020-12-01T21:16:38.799Z bravia:service:avContent Registering method getSchemeList (1.0) for avContent
2020-12-01T21:16:38.803Z bravia:service:avContent Registering method getSourceList (1.0) for avContent
2020-12-01T21:16:38.807Z bravia:service:avContent Registering parameter "scheme" for getSourceList (1.0)
2020-12-01T21:16:38.810Z bravia:service:avContent Registering method setPlayContent (1.0) for avContent
2020-12-01T21:16:38.815Z bravia:service:avContent Registering parameter "uri" for setPlayContent (1.0)
2020-12-01T21:16:38.816Z bravia:service:avContent Registering method getMethodTypes (1.0) for avContent
2020-12-01T21:16:38.817Z bravia:service:avContent Registering parameter "string" for getMethodTypes (1.0)
2020-12-01T21:16:38.819Z bravia:service:avContent Registering method getVersions (1.0) for avContent
[12/1/2020, 4:16:38 PM] [BraviaTVOS] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:138:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:194:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:115:18)
[12/1/2020, 4:16:45 PM] [Nest] Authentication successful.
[12/1/2020, 4:16:49 PM] [BraviaTVOS] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:138:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:194:10)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:115:46)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:177:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[12/1/2020, 4:16:54 PM] [Nest] initing thermostat (P) "Living Room Thermostat": deviceId: [redacted] structureId: [redacted]
[12/1/2020, 4:16:54 PM] [Nest] Temperature unit for Living Room Thermostat is: Fahrenheit
[12/1/2020, 4:16:54 PM] [Nest] Current temperature for Living Room Thermostat is: 20 °C / 68 °F
[12/1/2020, 4:16:54 PM] [Nest] Current humidity for Living Room Thermostat is: 40%
[12/1/2020, 4:16:54 PM] [Nest] Target temperature for Living Room Thermostat is: 20 °C / 68 °F
[12/1/2020, 4:16:54 PM] [Nest] Target heating/cooling state for Living Room Thermostat is: Heat
[12/1/2020, 4:16:54 PM] [Nest] Cooling threshold temperature for Living Room Thermostat is: 23.8 °C / 74.84 °F
[12/1/2020, 4:16:54 PM] [Nest] Heating threshold temperature for Living Room Thermostat is: 20 °C / 68 °F
[12/1/2020, 4:16:54 PM] [Nest] Online status for Living Room Thermostat is: true
[12/1/2020, 4:16:54 PM] [Nest] Skipping device [redacted] because it is not in the required structure. Has [redacted], looking for  [redacted].
[12/1/2020, 4:16:54 PM] [Nest] Skipping device  [redacted] because it is not in the required structure. Has  [redacted], looking for  [redacted].
[12/1/2020, 4:16:54 PM] [Nest] Skipping device  [redacted] because it is not in the required structure. Has  [redacted], looking for  [redacted].
[12/1/2020, 4:16:54 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId:  [redacted] structureId:  [redacted]
[12/1/2020, 4:16:54 PM] [Nest] Home Occupied for Home Occupied is: true
[12/1/2020, 4:16:54 PM] [Nest] Skipping device  [redacted] because it is not in the required structure. Has  [redacted], looking for  [redacted].
[12/1/2020, 4:16:59 PM] [Nest] Current heating/cooling state for Living Room Thermostat is: Heating
[12/1/2020, 4:16:59 PM] [BraviaTVOS] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:138:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:194:10)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:115:46)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:177:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by SeydX** [comment]
@lteffertiller 

Your TV supports the Sony API but can not find the requested method

Can you install the bravia modul pls 

``
sudo npm i -g @seydx/bravia@beta
``

and post the output here from the following command

``
bravia methods TVIPHERE --psk TVPSKHERE
``

**Comment by lteffertiller** [comment]
here ya go!

`[
  [
    {
      "endpoint": "accessControl",
      "version": false,
      "methods": []
    }
  ],
  [
    {
      "endpoint": "appControl",
      "version": "1.0",
      "availableMethods": [
        "getApplicationList",
        "setActiveApp",
        "getMethodTypes",
        "getVersions"
      ],
      "availableParams": {
        "getApplicationList": [],
        "setActiveApp": [
          "uri",
          "data"
        ],
        "getMethodTypes": [
          "string"
        ],
        "getVersions": []
      },
      "methods": [
        {
          "method": "getApplicationList",
          "in": [],
          "out": [
            {
              "title": "string",
              "uri": "string",
              "icon": "string",
              "data": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "setActiveApp",
          "in": [
            {
              "uri": "string",
              "data": "string"
            }
          ],
          "out": [],
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "in": [
            "string"
          ],
          "out": [
            "string",
            "string*",
            "string*",
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "in": [],
          "out": [
            "string*"
          ],
          "version": "1.0"
        }
      ]
    }
  ],
  [
    {
      "endpoint": "audio",
      "version": "1.0",
      "availableMethods": [
        "getVolumeInformation",
        "setAudioMute",
        "setAudioVolume",
        "getMethodTypes",
        "getVersions"
      ],
      "availableParams": {
        "getVolumeInformation": [],
        "setAudioMute": [
          "status"
        ],
        "setAudioVolume": [
          "target",
          "volume"
        ],
        "getMethodTypes": [
          "string"
        ],
        "getVersions": []
      },
      "methods": [
        {
          "method": "getVolumeInformation",
          "in": [],
          "out": [
            {
              "target": "string",
              "volume": "int",
              "mute": "bool",
              "maxVolume": "int",
              "minVolume": "int"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "setAudioMute",
          "in": [
            {
              "status": "bool"
            }
          ],
          "out": [
            "int"
          ],
          "version": "1.0"
        },
        {
          "method": "setAudioVolume",
          "in": [
            {
              "target": "string",
              "volume": "string"
            }
          ],
          "out": [
            "int"
          ],
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "in": [
            "string"
          ],
          "out": [
            "string",
            "string*",
            "string*",
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "in": [],
          "out": [
            "string*"
          ],
          "version": "1.0"
        }
      ]
    },
    {
      "endpoint": "audio",
      "version": "1.2",
      "availableMethods": [
        "setAudioVolume"
      ],
      "availableParams": {
        "setAudioVolume": [
          "target",
          "volume",
          "ui"
        ]
      },
      "methods": [
        {
          "method": "setAudioVolume",
          "in": [
            {
              "target": "string",
              "volume": "string",
              "ui": "string"
            }
          ],
          "out": [],
          "version": "1.2"
        }
      ]
    }
  ],
  [
    {
      "endpoint": "avContent",
      "version": "1.0",
      "availableMethods": [
        "getContentCount",
        "getContentList",
        "getCurrentExternalInputsStatus",
        "getSchemeList",
        "getSourceList",
        "setPlayContent",
        "getMethodTypes",
        "getVersions"
      ],
      "availableParams": {
        "getContentCount": [
          "source",
          "type"
        ],
        "getContentList": [
          "source",
          "stIdx",
          "cnt",
          "type"
        ],
        "getCurrentExternalInputsStatus": [],
        "getSchemeList": [],
        "getSourceList": [
          "scheme"
        ],
        "setPlayContent": [
          "uri"
        ],
        "getMethodTypes": [
          "string"
        ],
        "getVersions": []
      },
      "methods": [
        {
          "method": "getContentCount",
          "in": [
            {
              "source": "string",
              "type": "string"
            }
          ],
          "out": [
            {
              "count": "int"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getContentList",
          "in": [
            {
              "source": "string",
              "stIdx": "int",
              "cnt": "int",
              "type": "string"
            }
          ],
          "out": [
            {
              "uri": "string",
              "title": "string",
              "index": "int",
              "dispNum": "string",
              "originalDispNum": "string",
              "tripletStr": "string",
              "programNum": "int",
              "programMediaType": "string",
              "directRemoteNum": "int",
              "startDateTime": "string",
              "durationSec": "int",
              "channelName": "string",
              "fileSizeByte": "int",
              "isProtected": "bool",
              "isAlreadyPlayed": "bool"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getCurrentExternalInputsStatus",
          "in": [],
          "out": [
            {
              "uri": "string",
              "title": "string",
              "connection": "bool",
              "label": "string",
              "icon": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getSchemeList",
          "in": [],
          "out": [
            {
              "scheme": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getSourceList",
          "in": [
            {
              "scheme": "string"
            }
          ],
          "out": [
            {
              "source": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "setPlayContent",
          "in": [
            {
              "uri": "string"
            }
          ],
          "out": [],
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "in": [
            "string"
          ],
          "out": [
            "string",
            "string*",
            "string*",
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "in": [],
          "out": [
            "string*"
          ],
          "version": "1.0"
        }
      ]
    }
  ],
  [
    {
      "endpoint": "browser",
      "version": false,
      "methods": []
    }
  ],
  [
    {
      "endpoint": "cec",
      "version": false,
      "methods": []
    }
  ],
  [
    {
      "endpoint": "encryption",
      "version": false,
      "methods": []
    }
  ],
  [
    {
      "endpoint": "guide",
      "version": "1.0",
      "availableMethods": [
        "getServiceProtocols",
        "getSupportedApiInfo",
        "getMethodTypes",
        "getVersions"
      ],
      "availableParams": {
        "getServiceProtocols": [],
        "getSupportedApiInfo": [
          "services"
        ],
        "getMethodTypes": [
          "string"
        ],
        "getVersions": []
      },
      "methods": [
        {
          "method": "getServiceProtocols",
          "in": [],
          "out": [
            "string",
            "string*"
          ],
          "version": "1.0"
        },
        {
          "method": "getSupportedApiInfo",
          "in": [
            {
              "services": "string*"
            }
          ],
          "out": [
            {
              "service": "string",
              "protocols": "string*",
              "apis": "ApiInfo[]"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "in": [
            "string"
          ],
          "out": [
            "string",
            "string*",
            "string*",
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "in": [],
          "out": [
            "string*"
          ],
          "version": "1.0"
        }
      ]
    }
  ],
  [
    {
      "endpoint": "recording",
      "version": false,
      "methods": []
    }
  ],
  [
    {
      "endpoint": "system",
      "version": "1.0",
      "availableMethods": [
        "getCurrentTime",
        "getInterfaceInformation",
        "getNetworkSettings",
        "getPowerStatus",
        "getRemoteControllerInfo",
        "getSystemInformation",
        "requestReboot",
        "setPowerStatus",
        "getMethodTypes",
        "getVersions"
      ],
      "availableParams": {
        "getCurrentTime": [],
        "getInterfaceInformation": [],
        "getNetworkSettings": [
          "netif"
        ],
        "getPowerStatus": [],
        "getRemoteControllerInfo": [],
        "getSystemInformation": [],
        "requestReboot": [],
        "setPowerStatus": [
          "status"
        ],
        "getMethodTypes": [
          "string"
        ],
        "getVersions": []
      },
      "methods": [
        {
          "method": "getCurrentTime",
          "in": [],
          "out": [
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getInterfaceInformation",
          "in": [],
          "out": [
            {
              "productCategory": "string",
              "productName": "string",
              "modelName": "string",
              "serverName": "string",
              "interfaceVersion": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getNetworkSettings",
          "in": [
            {
              "netif": "string"
            }
          ],
          "out": [
            {
              "netif": "string",
              "hwAddr": "string",
              "ipAddrV4": "string",
              "ipAddrV6": "string",
              "netmask": "string",
              "gateway": "string",
              "dns": "string*"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getPowerStatus",
          "in": [],
          "out": [
            {
              "status": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getRemoteControllerInfo",
          "in": [],
          "out": [
            {
              "bundled": "bool",
              "type": "string"
            },
            {
              "name": "string",
              "value": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "getSystemInformation",
          "in": [],
          "out": [
            {
              "product": "string",
              "region": "string",
              "language": "string",
              "model": "string",
              "serial": "string",
              "macAddr": "string",
              "name": "string",
              "generation": "string",
              "area": "string",
              "cid": "string"
            }
          ],
          "version": "1.0"
        },
        {
          "method": "requestReboot",
          "in": [],
          "out": [],
          "version": "1.0"
        },
        {
          "method": "setPowerStatus",
          "in": [
            {
              "status": "bool"
            }
          ],
          "out": [],
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "in": [
            "string"
          ],
          "out": [
            "string",
            "string*",
            "string*",
            "string"
          ],
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "in": [],
          "out": [
            "string*"
          ],
          "version": "1.0"
        }
      ]
    },
    {
      "endpoint": "system",
      "version": "1.1",
      "availableMethods": [
        "getCurrentTime"
      ],
      "availableParams": {
        "getCurrentTime": []
      },
      "methods": [
        {
          "method": "getCurrentTime",
          "in": [],
          "out": [
            {
              "dateTime": "string",
              "timeZoneOffsetMinute": "int",
              "dstOffsetMinute": "int"
            }
          ],
          "version": "1.1"
        }
      ]
    }
  ],
  [
    {
      "endpoint": "videoScreen",
      "version": false,
      "methods": []
    }
  ]
]
`

**Comment by SeydX** [comment]
Your TV does not seem to fully support the Sony API. The problem is that your TV is not able to tell WHAT the TV is playing. And this is exactly the endpoint the plugin uses to work.

I just wonder why your TV, which is so up-to-date, only partially supports the API.

**Comment by lteffertiller** [comment]
Very weird indeed! Totally fine by me, but thanks for the help :)

**Comment by robboz4** [comment]
I'm having the same issue and my TV is dated October 2020. I just installed it and tried this plugin but get the same errors.

**Comment by SeydX** [comment]
@robboz4 

Tried a another bravia plugin with success before?

**Comment by robboz4** [comment]
Couldn't get the first plugin I tried to recognize the TV. So uninstalled it and tried this one. Power is working but no apps for stations.

**Comment by donavanbecker** [comment]
@SeydX I couldn't get your plugin to work with a newer tv that was bought about October 2020. I tried this [plugin](https://github.com/benzman81/homebridge-bravia-simple) and it connected, but it registers the TV as a bridged TV so doesn't have the TV icon.

Figured I would share if you wanted to look into this issue?

**Comment by SeydX** [comment]
@donavanbecker 

Same error as mentioned here?

**Comment by donavanbecker** [comment]
> @donavanbecker
> 
> Same error as mentioned here?

no I didn't get an error. the plugin turned the tv on and off. but it didn't publish the tv as a external acessory like your plugin does. So it won't work with control center either.

**Comment by SeydX** [comment]
@donavanbecker 

Normally, it is not displayed if you have previously used another plugin with the same tv name.

Tried with another name in config.json?

**Comment by donavanbecker** [comment]
> @donavanbecker
> 
> Normally, it is not displayed if you have previously used another plugin with the same tv name.
> 
> Tried with another name in config.json?

why? I just wanted to let you know that that plugin is working with this kind of TV, and I know yours isn't so I figured I would point you to that plugin so you could see the difference.

only problem with that plugin is not registering as external accessory but thats okay.

**Comment by calvinngkk** [comment]
Same with my bravia TV, connect using PSK as PIN dont work, teied others but others uses PIN unfortunately no PIN appear on TV

my tv model : Sony Bravia 55x750H / x7500H
Year 2020 model Android Pie

[21/01/2021, 10:34:05 am] [Bravia TV] Bravia TV: Polling tv state
[21/01/2021, 10:34:05 am] [Bravia TV] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:150:13)
    at ServiceProtocol.invoke (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:164:30)
    at tvAccessory.poll (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:117:46)
    at Timeout._onTimeout (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:179:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[21/01/2021, 10:34:15 am] [Bravia TV] Bravia TV: Polling tv state
[21/01/2021, 10:34:15 am] [Bravia TV] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:150:13)
    at ServiceProtocol.invoke (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:164:30)
    at tvAccessory.poll (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:117:46)
    at Timeout._onTimeout (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:179:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[21/01/2021, 10:34:25 am] [Bravia TV] Bravia TV: Polling tv state
[21/01/2021, 10:34:25 am] [Bravia TV] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:150:13)
    at ServiceProtocol.invoke (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:164:30)
    at tvAccessory.poll (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:117:46)
    at Timeout._onTimeout (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:179:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[21/01/2021, 10:34:35 am] [Bravia TV] Bravia TV: Polling tv state
[21/01/2021, 10:34:35 am] [Bravia TV] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:150:13)
    at ServiceProtocol.invoke (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\node_modules\@seydx\bravia\src\service-protocol.js:164:30)
    at tvAccessory.poll (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:117:46)
    at Timeout._onTimeout (C:\Users\calvi\AppData\Roaming\npm\node_modules\homebridge-bravia-tvos\src\accessories\tv.js:179:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by SeydX** [comment]
v4.1.10 is online, can u try it all pls
