### ISSUE TITLE
TV icon not showing up in IOS app

### ISSUE THREAD

**Issue by robboz4** [SeydX/homebridge-bravia-tvos#118]
I have installed and configured the plugin but I have the issue listed previously with errors in the log and zero entries in the test tool you suggested we use. I also have two icons both labeled with Sony TV. One with a speaker and the other a TV image. I can turn the TV on and off from the config-ux icons, but these icons do not show up in the app on the iPhone. 
Any clue as what I may have got wrong with the configuration of the plugin?

{
            "platform": "BraviaOSPlatform",
            "name": "BraviaTVOS",
            "tvs": [
                {
                    "name": "Sony TV",
                    "ip": "192.168.1.19",
                    "port": 80,
                    "timeout": 5,
                    "psk": "0000",
                    "inputs": [
                        "[extInput:hdmi] HDMI 1"
                    ],
                    "apps": [
                        "Netflix",
                        "Hulu",
                        "Disney+"
                    ],
                    "speaker": {
                        "output": "speaker"
                    }
                }
            ]
        }

-----

Thanks!

**Comment by SeydX** [comment]
@robboz4 

Can u post a screenshot pls

**Comment by robboz4** [comment]
![Screen Shot 2020-12-11 at 4 14 30 PM](https://user-images.githubusercontent.com/3642405/101966310-267c9c80-3bcc-11eb-8886-c2c7fbad6683.png)
 Log file entry

[12/11/2020, 4:15:16 PM] [BraviaTVOS] Error: Requested method (getPlayingContentInfo) could not be found!
    at ServiceProtocol.checkApiMethod (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:150:13)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/src/service-protocol.js:164:30)
    at tvAccessory.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:117:46)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/tv.js:179:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by SeydX** [comment]
@robboz4 

You need to add the tv like a bridge to apple home

See here

https://github.com/SeydX/homebridge-bravia-tvos/issues/108

**Comment by robboz4** [comment]
Got it thanks a bunch!
