### ISSUE TITLE
Unable to pull app name

### ISSUE THREAD

**Issue by Hexin-Lin-1024** [SeydX/homebridge-bravia-tvos#129]
Hi
The plugin worked well but it could not show the right name of the app.
Here's Log: 
[20/01/2021, 18:59:28] Homebridge is running on port 51826.
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding tv service
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding speaker service
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: HDMI 1
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"HDMI 1","identifier":20,"type":"input","subtype":"hdmi1-5w2d4","inputType":3,"deviceType":4}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: HDMI 2
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"HDMI 2","identifier":21,"type":"input","subtype":"hdmi2-3aei4","inputType":3,"deviceType":4}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: HDMI 3 (eARC/ARC)
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"HDMI 3 (eARC/ARC)","identifier":22,"type":"input","subtype":"hdmi3(earc/arc)-nyjni","inputType":3,"deviceType":4}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: HDMI 4
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"HDMI 4","identifier":23,"type":"input","subtype":"hdmi4-7qg0b","inputType":3,"deviceType":4}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: NewTV极光
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"NewTV极光","type":"app","subtype":"newtv极光-up34z","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 音乐
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"音乐","identifier":1,"type":"app","subtype":"音乐-3kvts","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 媒体播放器
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"媒体播放器","identifier":2,"type":"app","subtype":"媒体播放器-btfnl","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 电视
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"电视","identifier":3,"type":"app","subtype":"电视-tmfq5","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 应用商店
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"应用商店","identifier":4,"type":"app","subtype":"应用商店-narx3","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 应用助手
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"应用助手","identifier":5,"type":"app","subtype":"应用助手-buxe2","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 智能家居
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"智能家居","identifier":6,"type":"app","subtype":"智能家居-3zind","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 会员尊享
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"会员尊享","identifier":7,"type":"app","subtype":"会员尊享-omwzt","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 帮助
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"帮助","identifier":8,"type":"app","subtype":"帮助-k7aq5","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: Sony Select
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"Sony Select","identifier":9,"type":"app","subtype":"sonyselect-zrf68","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 计时器
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"计时器","identifier":10,"type":"app","subtype":"计时器-1s531","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: 当贝酷狗音乐
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"当贝酷狗音乐","identifier":11,"type":"app","subtype":"当贝酷狗音乐-8lmsr","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Adding new input: MGTV-芒果TV
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"name":"MGTV-芒果TV","identifier":12,"type":"app","subtype":"mgtv-芒果tv-pr280","inputType":10,"deviceType":0}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Configured!
[20/01/2021, 18:59:29] KD-65X9500H is running on port 43617.
[20/01/2021, 18:59:29] Please add [KD-65X9500H] manually in Home app. Setup Code: 327-43-835
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 18:59:29] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway.
[20/01/2021, 18:59:39] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 18:59:40] [BraviaTVOS] KD-65X9500H: [40005,"Display Is Turned off"]
[20/01/2021, 18:59:44] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8080
[20/01/2021, 18:59:50] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 18:59:50] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 18:59:50] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 18:59:50] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:00] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:00] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:00] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:00] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:10] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:10] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:10] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:10] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:20] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:20] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:20] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:21] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:31] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:31] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:31] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:31] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:41] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:41] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:41] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:41] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:00:51] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:00:51] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:00:51] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:00:51] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:01] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:01] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:01] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:01] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:11] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:11] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:11] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:11] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:21] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:21] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:21] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:21] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:31] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:32] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:32] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:32] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:42] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:42] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:42] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:42] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:01:52] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:01:52] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:01:52] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:01:52] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:02] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:02] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:02] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:02] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:12] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:12] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:12] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:12] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:22] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:22] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:22] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:22] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:32] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:32] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:32] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:32] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:42] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:42] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:42] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:43] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:02:53] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:02:53] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:02:53] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:02:53] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:03] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:03] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:03] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:03] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:13] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:13] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:13] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:13] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:23] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:23] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:23] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:23] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:33] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:33] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:33] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:33] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:43] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:43] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:43] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:43] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
[20/01/2021, 19:03:53] [BraviaTVOS] KD-65X9500H: Polling tv state
[20/01/2021, 19:03:53] [BraviaTVOS] KD-65X9500H: {"source":"application","title":"App","uri":false}
[20/01/2021, 19:03:53] [BraviaTVOS] KD-65X9500H: Polling speaker state
[20/01/2021, 19:03:54] [BraviaTVOS] KD-65X9500H: [{"target":"speaker","volume":16,"mute":false,"maxVolume":100,"minVolume":0}]
Config:
"tvs": [
                {
                    "name": "KD-65X9500H",
                    "ip": "192.168.3.56",
                    "port": 80,
                    "timeout": 5,
                    "psk": "password",
                    "refreshInputs": false,
                    "inputs": [
                        "extInput:hdmi"
                    ],
                    "apps": [
                        "NewTV极光",
                        "音乐",
                        "媒体播放器",
                        "电视",
                        "应用商店",
                        "应用助手",
                        "智能家居",
                        "会员尊享",
                        "帮助",
                        "Sony Select",
                        "计时器",
                        "当贝酷狗音乐",
                        "MGTV-芒果TV"
                    ],
                    "speaker": {
                        "output": "speaker",
                        "increaseBy": 1,
                        "reduceBy": 1,
                        "accType": "lightbulb"
                    }
PS: Homeassistant also failed getting app name.
TV: Sony KD-65X9500H CN VER
Thanks a lot
Ken

**Comment by SeydX** [comment]
@Hexin-Lin-1024 

can you give me a better example of the issue?

What does it show instead?

**Comment by Hexin-Lin-1024** [comment]
When I switch the app
![pic (2)](https://user-images.githubusercontent.com/63279857/105344271-acedba80-5c1d-11eb-9293-c63cc6baad00.jpg)
it works
but a few seconds later
![pic](https://user-images.githubusercontent.com/63279857/105344384-d0186a00-5c1d-11eb-8cf1-940a073d5154.jpg)
it shows "NewTV极光" again in apple home (but actually not)

**Comment by Hexin-Lin-1024** [comment]
I found some error logs
[23/01/2021, 12:08:24] [Homebridge UI] [homebridge-bravia-tvos] events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at UiServer.ready (/usr/local/node/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new UiServer (/usr/local/node/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:28:10)
    at /usr/local/node/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:397:10
    at Object.<anonymous> (/usr/local/node/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:398:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on process instance at:
    at internal/child_process.js:836:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by SeydX** [comment]
https://github.com/SeydX/homebridge-bravia-tvos/issues/124
