### ISSUE TITLE
Unable to refresh inputs

### ISSUE THREAD

**Issue by prasad-edlabadka** [SeydX/homebridge-bravia-tvos#154]
When I refresh the TV, I get following errors

[1/8/2021, 12:19:51 pm] [Homebridge UI] [homebridge-bravia-tvos] Incoming Request: /refreshTV
[1/8/2021, 12:19:51 pm] [Homebridge UI] [homebridge-bravia-tvos] Incoming Request: /refreshTV
[1/8/2021, 12:19:54 pm] [Homebridge UI] [homebridge-bravia-tvos] Main TV: An error occured during fetching applications!
[1/8/2021, 12:19:54 pm] [Homebridge UI] [homebridge-bravia-tvos] Main TV: An error occured during fetching applications!
[1/8/2021, 12:19:54 pm] [Homebridge UI] [homebridge-bravia-tvos] TypeError: response.result[0].map is not a function
    at exports.fetchApps (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.utils.js:14:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UiServer.getApps (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:108:12)
    at async UiServer.refreshTV (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:172:18)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[1/8/2021, 12:19:54 pm] [Homebridge UI] [homebridge-bravia-tvos] TypeError: response.result[0].map is not a function
    at exports.fetchApps (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.utils.js:14:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UiServer.getApps (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:108:12)
    at async UiServer.refreshTV (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:172:18)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[1/8/2021, 12:20:05 pm] [Homebridge UI] [homebridge-bravia-tvos] TypeError: commands.forEach is not a function
    at UiServer.refreshTV (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:220:16)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[1/8/2021, 12:20:05 pm] [Homebridge UI] [homebridge-bravia-tvos] TypeError: commands.forEach is not a function
    at UiServer.refreshTV (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:220:16)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)

**Comment by prasad-edlabadka** [comment]
Downgrading to 4.1.12 works fine.

**Comment by bjoernmayer** [comment]
Inputs also do not show up for me on `5.0.1`.
Log:
```
[8/11/2021, 11:16:59 AM] [BraviaTVOS] [DEBUG] Sony: Fetching inputs
[8/11/2021, 11:16:59 AM] [Hue] Wohnzimmer Decke: set homekit transition control to ""
[8/11/2021, 11:16:59 AM] [Hue] Kommode: set homekit transition control to ""
[8/11/2021, 11:17:05 AM] [BraviaTVOS] Sony: An error occured during fetching applications!
[8/11/2021, 11:17:05 AM] [BraviaTVOS] Error: Internal Server Error
    at exports.request (/homebridge/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/request.js:80:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ServiceProtocol.invoke (/homebridge/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:89:12)
    at exports.fetchInputs (/homebridge/node_modules/homebridge-bravia-tvos/src/accessories/accessory.utils.js:39:22)
    at Setup (/homebridge/node_modules/homebridge-bravia-tvos/src/accessories/accessory.setup.js:145:26)
    at BraviaOSPlatform.didFinishLaunching (/homebridge/node_modules/homebridge-bravia-tvos/src/platform.js:38:5) {
  title: 'Invalid Response',
  code: 500,
  soap: {},
  url: 'http://192.168.178.24/sony/avContent'
}
```

**Comment by SeydX** [comment]
v5.0.2 should fix this issue
