### ISSUE TITLE
Internal Server Error on getCurrentExternalInputsStatus

### ISSUE THREAD

**Issue by bjoernmayer** [SeydX/homebridge-bravia-tvos#156]
Heyho,

currently my TV does not want to deliver its external inputs to the homebridge plugin.

```
[BraviaTVOS] Error: Internal Server Error
    at exports.request (/homebridge/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/request.js:80:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ServiceProtocol.invoke (/homebridge/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:89:12)
    at exports.fetchInputs (/homebridge/node_modules/homebridge-bravia-tvos/src/accessories/accessory.utils.js:39:22)
    at Setup (/homebridge/node_modules/homebridge-bravia-tvos/src/accessories/accessory.setup.js:145:26)
    at BraviaOSPlatform.didFinishLaunching (/homebridge/node_modules/homebridge-bravia-tvos/src/platform.js:38:5) {
  title: 'Invalid Response',
  code: 500,
  soap: {},
  url: 'http://192.168.178.24/sony/avContent'
}
```

I tried requesting the endpoint manually using curl:
```
curl -X "POST" "http://192.168.178.24/sony/avContent" \
     -H 'X-Auth-PSK: 1234' \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -d $'{
    "method": "getCurrentExternalInputsStatus",
    "id": 105,
    "params": [],
    "version": "1.1"
}
'
```

The TV answers with
```{
  "error": [
    500,
    "Internal Server Error"
  ],
  "id": 105
}
```

I've seen your issues https://github.com/SeydX/homebridge-bravia-tvos/issues/75 where you say that this will be fixed in version 4. 
Do you know by any chance how you fixed it? I cannot find the corresponding commit in the log =/

**Comment by bjoernmayer** [comment]
Sometimes it is too easy.
My tv was running in the other room and I thought: "I wonder if the api still works, if I turn it off". 
et voila:

`getCurrentExternalInputsStatus` also works now

**Comment by bjoernmayer** [comment]
Ooops. I didn't mean to close this issue just yet. But feel free to do so

**Comment by bjoernmayer** [comment]
It gets weirder and weirder.
I found out that the endpoint works for a few seconds after the tv was turned on. Often this is not enough for all cec devices to report their status.
Now the best part: I turned on one of my devices first, and then the tv was turned on via cec. Now the endpoint keeps working.

Weirdest fix ever

**Comment by SeydX** [comment]
It seems you were able to fix the problem? ^^
