### ISSUE TITLE
[ERROR] Error: Failed to load data, status code:500

### ISSUE THREAD

**Issue by s-bz** [SeydX/homebridge-bravia-tvos#16]
Hi,
I'm hitting an unexpected error on Sony TV KD-49X8000C and would appreciate if you could help.

1. I'm able to get the list of apps by running terminal command so the IP and PSK are correct.
2. I'm running homebridge as a docker container on a Synology NAS. Other plugins work OK. It's set up through https://github.com/oznu/homebridge-syno-spk with Homebridge Version 0.4.46
3. I enabled debug log in Homebridge, hopefully this is enough information.

Thanks,
Sam

```
[2/10/2019, 10:50:33 PM] [BraviaOSPlatform] [ERROR] Sony Android: An error occured by getting inputs, trying again...
[2/10/2019, 10:50:33 PM] [BraviaOSPlatform] [ERROR] Error: Failed to load data, status code:500
[2/10/2019, 10:50:33 PM] [BraviaOSPlatform] [ERROR] Error: Failed to load data, status code:500
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-bravia-tvos/src/platform.js:77:18)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

i see this bit of information in the log
`Plugin /homebridge/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v10.15.1. You may need to upgrade your installation of Node.` but i saw your comment on https://github.com/SeydX/homebridge-bravia-tvos/issues/5 so i assume it's a non-issue

**Comment by s-bz** [comment]
I tried to install https://www.npmjs.com/package/homebridge-sony-television 
It worked right away. I can turn on/off the TV using that plugin, switch inputs, etc.

The interesting part is that toggling that other plugin made your plugin start working. 

```
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Getting data from Sony Android (192.168.7.53:80)
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Found new inputs, checking config for apps...
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Found apps in config, storing in cache...
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Checking Sony Android for channels...
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Found following sources: ["Analog","Dvbt"]
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Storing Sony TV Data in cache...
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Connecting to 192.168.7.53
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Configuring accessory: Sony Android
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Adding new Input Source: HDMI 1
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Adding new Input Source: HDMI 2/MHL
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Adding new Input Source: HDMI 3
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Adding new Input Source: HDMI 4/ARC
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Adding new Input Source: ExpressVPN
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Inputlist finished
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: Welcome to Sony Bravia TV OS 2.0.0 - Below your Identifier list to create rules in 3rd party apps
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: (0) HDMI 1
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: (1) HDMI 2/MHL
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: (2) HDMI 3
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: (3) HDMI 4/ARC
[2/10/2019, 11:50:53 PM] [BraviaOSPlatform] [INFO] Sony Android: (4) ExpressVPN
HAP Warning: Characteristic 000000EA-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.

```

**Comment by SeydX** [comment]
Status code 500 means internal server error, maybe ip adress incorrect? Or there are too many attempts to connect to your tv, that can be caused if u use many plugins for your tv and everyone tries to poll the state

The tv needs to be turned on for initial request, only the first time or if you change your config

**Comment by raphiegg** [comment]
I have the exact same issue with a Sony KD-55A1.
In my case, the Homebridge runs alone on a Raspberry Pi 3

`[2019-2-24 23:36:18] [BraviaOSPlatform] [ERROR] Sony TV: An error occured by getting inputs, trying again...
[2019-2-24 23:36:18] [BraviaOSPlatform] [ERROR] Error: Failed to load data, status code:500
[2019-2-24 23:36:18] [BraviaOSPlatform] [ERROR] Error: Failed to load data, status code:500
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/platform.js:77:18)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:445:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
`

**Comment by SeydX** [comment]
Hello, im currently working on v3 with a rewritten code , i will check this in v3

**Comment by SeydX** [comment]
Hello, im currently working on v3, the beta is now available!

How to download and configure:
https://github.com/SeydX/homebridge-bravia-tvos/issues/32
