### ISSUE TITLE
Reoccuring error "EHOSTUNREACH"

### ISSUE THREAD

**Issue by SeanHama** [SeydX/homebridge-bravia-tvos#161]
Hi Guys, I keep getting this issue whilst the TV is off, when the TV is on the error goes away.

Error: connect EHOSTUNREACH 192.168.0.166:80
    at exports.request (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/request.js:104:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:89:12)
    at Handler.getTelevisionState (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:16:24)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:458:7) {
  title: 'No Response',
  code: 'EHOSTUNREACH',
  soap: {},
  url: 'http://192.168.0.166/sony/avContent'

<img width="1103" alt="Screen Shot 2021-09-01 at 7 53 24 am" src="https://user-images.githubusercontent.com/57736130/131580928-38023ea9-5fd1-4018-9f9b-c01fff813342.png">

**Comment by SeydX** [comment]
Added new option `"oldModel"` to config.json to hide the error messages if API is not available

**Comment by lukasmalkmus** [comment]
I still get the error with `v5.0.2`:

```
[9/20/2021, 11:08:45 AM] [BraviaTVOS] TV: An error occured during getting television state!
[9/20/2021, 11:08:45 AM] [BraviaTVOS] TV: connect EHOSTUNREACH 192.168.178.23:80
```

I'm also using `"wol": true`.

**Comment by SeydX** [comment]
can u try latest Beta pls v5.0.6-beta.5

``sudo npm i -g homebridge-bravia-tvos@beta``

**Comment by SeydX** [comment]
v5.0.6 is online

**Comment by lukasmalkmus** [comment]
Fixed it for me :)
