### ISSUE TITLE
Issue connecting TV

### ISSUE THREAD

**Issue by sedestrian** [SeydX/homebridge-bravia-tvos#172]
Hello,
I'm trying to connect a Bravia 55XE9005 with your plugin but I'm encountering a problem.
I insert the ip and psk and the log prints this error:
```
[20/10/2021, 14:32:48] [Homebridge UI] [homebridge-bravia-tvos] Error: Service Method "getSystemInformation" not known!
    at Bravia.exec (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/bravia.js:314:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UiServer.checkAuth (/usr/local/lib/node_modules/homebridge-bravia-tvos/homebridge-ui/server.js:100:12)
    at async UiServer.processRequest (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30) {
  title: 'Unknown Service Method: "getSystemInformation"',
  code: 'APIERROR',
  soap: {},
  payload: [],
  url: 'http://192.168.86.42/sony/system'
}
```

Also I tried running the command `bravia methods 192.168.86.42` and the output is the following:
```
[
  {
    "service": "accessControl",
    "methods": []
  },
  {
    "service": "appControl",
    "methods": []
  },
  {
    "service": "audio",
    "methods": []
  },
  {
    "service": "avContent",
    "methods": []
  },
  {
    "service": "browser",
    "methods": []
  },
  {
    "service": "cec",
    "methods": []
  },
  {
    "service": "contentshare",
    "methods": []
  },
  {
    "service": "encryption",
    "methods": []
  },
  {
    "service": "guide",
    "methods": []
  },
  {
    "service": "recording",
    "methods": []
  },
  {
    "service": "system",
    "methods": []
  },
  {
    "service": "video",
    "methods": []
  },
  {
    "service": "videoScreen",
    "methods": []
  }
]
```

**Comment by sedestrian** [comment]
Apparently I just had to restart the TV
