### ISSUE TITLE
Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by mensa84** [SeydX/homebridge-bravia-tvos#211]
Hello,

thanks for that plugin, it is working fine with my KD65-AF8 in the living room.

But with the older KD in the bedroom I am getting that log entries every few seconds when it is powered off, although I have configured it as "old" device correctly (I think). When it's powered on, everything is fine.

Is there any way how I may fix that?
Both are connected via WiFi.

```
[6/25/2023, 10:25:30 AM] [BraviaTVOS] Error: Error: connect EHOSTUNREACH 192.168.1.30:80
    at ServiceProtocol.describe (/usr/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:68:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /usr/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/bravia.js:257:22
    at async Promise.all (index 0)
    at Bravia.describe (/usr/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/bravia.js:255:27)
    at Bravia.exec (/usr/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/bravia.js:289:28)
    at Handler.getTelevisionState (/usr/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:18:24)
    at Handler.poll (/usr/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:559:7)
```

```
            "name": "BraviaTVOS",
            "platform": "BraviaOSPlatform",
            "debug": true,
            "warn": true,
            "error": true,
            "extendedError": true,
            "tvs": [
                {
                    "active": true,
                    "name": "Wohnzimmer TV",
                    "ip": "192.168.1.21",
                    "port": 80,
                    "psk": "03145154",
                    "manufacturer": "Sony",
                    "model": "Bravia",
                    "serialNumber": "00000000",
                    "refreshInputs": false,
                    "wol": false,
                    "oldModel": false,
                    "polling": 10,
                    "sheduledRefresh": 12,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "identifier": "Wohnzimmer App",
                            "source": "cec"
                        },
                        {
                            "name": "PlayStation 5",
                            "identifier": "PlayStation 5",
                            "source": "cec"
                        }
                    ],
                    "displayOrder": [
                        "inputs",
                        "apps",
                        "channels",
                        "commands",
                        "macros"
                    ],
                    "speaker": {
                        "active": false,
                        "output": "speaker",
                        "increaseBy": 1,
                        "reduceBy": 1,
                        "accType": "lightbulb"
                    },
                    "commands": [],
                    "macros": [],
                    "remote": []
                },
                {
                    "active": true,
                    "name": "Schlafzimmer TV",
                    "ip": "192.168.1.30",
                    "mac": "14:2d:27:0b:de:33",
                    "port": 80,
                    "psk": "03145154",
                    "manufacturer": "Sony",
                    "model": "Bravia",
                    "serialNumber": "00000000",
                    "refreshInputs": false,
                    "wol": true,
                    "oldModel": true,
                    "polling": 10,
                    "sheduledRefresh": 12,
                    "displayOrder": [
                        "inputs",
                        "apps",
                        "channels",
                        "commands",
                        "macros"
                    ],
                    "speaker": {
                        "active": false,
                        "output": "speaker",
                        "increaseBy": 1,
                        "reduceBy": 1,
                        "accType": "lightbulb"
                    },
                    "channels": [],
                    "commands": [],
                    "macros": [],
                    "remote": []
                }
```

**Comment by mensa84** [comment]
Plugin not maintained anymore???
