### ISSUE TITLE
An error occured while handling accessories! iOS 13.1.3

### ISSUE THREAD

**Issue by LinusJun** [SeydX/homebridge-bravia-tvos#73]
[11/15/2019, 11:28:07 PM] Loaded config.json with 0 accessories and 1 platforms.,
[11/15/2019, 11:28:07 PM] ---,
[11/15/2019, 11:28:07 PM] Plugin /homebridge/node_modules/homebridge-bravia-tvos requires Node version of ^8.9.1 which does not satisfy the current Node version of v10.16.3. You may need to upgrade your installation of Node.,
[11/15/2019, 11:28:07 PM] Loaded plugin: homebridge-bravia-tvos,
[11/15/2019, 11:28:08 PM] Registering platform 'homebridge-bravia-tvos.BraviaOSPlatform',
[11/15/2019, 11:28:08 PM] ---,
[11/15/2019, 11:28:08 PM] Loaded plugin: homebridge-dummy,
[11/15/2019, 11:28:08 PM] Registering accessory 'homebridge-dummy.DummySwitch',
[11/15/2019, 11:28:08 PM] ---,
[11/15/2019, 11:28:08 PM] Loaded plugin: homebridge-config-ui-x,
[11/15/2019, 11:28:08 PM] Registering platform 'homebridge-config-ui-x.config',
[11/15/2019, 11:28:08 PM] ---,
[11/15/2019, 11:28:08 PM] Loading 1 platforms...,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] Initializing BraviaOSPlatform platform...,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] **************************************************************,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] BraviaOSPlatform v3.0.6 by SeydX,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] GitHub: https://github.com/SeydX/homebridge-bravia-tvos,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] Email: seyd55@outlook.de,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] **************************************************************,
[11/15/2019, 11:28:08 PM] [BraviaOSPlatform] start success...,
[11/15/2019, 11:28:08 PM] Loading 0 accessories...,
Setup Payload:,
X-HM://0023ISYX27L6E,
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:,
[11/15/2019, 11:28:09 PM] [BraviaOSPlatform] [INFO] Adding new accessory: Sony TV,
[11/15/2019, 11:28:09 PM] [BraviaOSPlatform] [INFO] Sony TV: Initalizing Bravia API with IP Control,
[11/15/2019, 11:28:09 PM] [BraviaOSPlatform] [INFO] Sony TV: Cheking authentication...,
[11/15/2019, 11:28:09 PM] Homebridge is running on port 51210.,
[11/15/2019, 11:28:14 PM] [BraviaOSPlatform] [INFO] Sony TV: Authenticated!,
[11/15/2019, 11:28:14 PM] [BraviaOSPlatform] [WARN] Sony TV: TV currently offline, trying to connect (this can take up to 5 minutes) ...,
[11/15/2019, 11:28:16 PM] [Config] Homebridge Config UI X v4.6.1 is listening on 0.0.0.0 port 8081,
[11/15/2019, 11:28:27 PM] [BraviaOSPlatform] [INFO] Sony TV: Connection established!,
[11/15/2019, 11:28:27 PM] [BraviaOSPlatform] [ERROR] Sony TV: An error occured while handling accessories!,
(node:652) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON,
    at JSON.stringify (<anonymous>),
    at TelevisionAccessory.handleAccessory (/homebridge/node_modules/homebridge-bravia-tvos/src/accessory.js:127:30),
    at process._tickCallback (internal/process/next_tick.js:68:7),
(node:652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2),
(node:652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LinusJun** [comment]
Here is my config.json
{
"bridge": {
  ...
},
"accessories": [],
"platforms": [
   {
     "platform": "BraviaOSPlatform",
     "tvs": [
       {
         "name": "Sony TV",
         "ip": "172.31.6.239",
         "port": 9999,
       }
     ],
     "interval": 10
   }
]
}

**Comment by Soldiiier** [comment]
why is your port 9999? is that something you've set on the tv?

**Comment by SeydX** [comment]
Try v3.0.7 pls
