### ISSUE TITLE
Type error indexOF of undefined

### ISSUE THREAD

**Issue by GaoVang2005** [SeydX/homebridge-bravia-tvos#8]
TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (C:\Users\vietd\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:108:12)
    at Server._loadPlatforms (C:\Users\vietd\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:316:45)
    at Server.run (C:\Users\vietd\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:86:36)
    at module.exports (C:\Users\vietd\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:45:10)
    at Object.<anonymous> (C:\Users\vietd\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by SeydX** [comment]
Node version?
Homebridge version?

It seems u need to update it to latest version

**Comment by SeydX** [comment]
Please update homebridge to 0.4.46 and try it with v2 of this plugin
